(function(){
	var layout = [
		[
			{name:'logo'},
			{name:'spacer', size: 19},
			{name:'num', type:'indicators'},
			{name:'caps', type:'indicators'},
			{name:'scroll', type:'indicators'},
			{name:'spacer', size: 3},
			{name:'game', type:'indicators'},
			{name:'spacer', size: 2},
			{name:'backlight', type:'indicators'},
			{name:'spacer', size: 1},
			{name:'mute', type:'multimedia'}
		],
		[
			{name:'esc', type:'functions'},
			{name:'spacer', size: 1},
			{name:'f1', type:'fkeys'},
			{name:'f2', type:'fkeys'},
			{name:'f3', type:'fkeys'},
			{name:'f4', type:'fkeys'},
			{name:'spacer', size: 1},
			{name:'f5', type:'fkeys'},
			{name:'f6', type:'fkeys'},
			{name:'f7', type:'fkeys'},
			{name:'f8', type:'fkeys'},
			{name:'spacer', size: 1},
			{name:'f9', type:'fkeys'},
			{name:'f10', type:'fkeys'},
			{name:'f11', type:'fkeys'},
			{name:'f12', type:'fkeys'},
			{name:'spacer', size: 1},
			{name:'print_screen', type:'functions'},
			{name:'scroll_lock', type:'functions'},
			{name:'pause_break', type:'functions'},
			{name:'spacer', size: 1},
			{name:'play', type:'multimedia'},
			{name:'stop', type:'multimedia'},
			{name:'prev', type:'multimedia'},
			{name:'next', type:'multimedia'}
		],
		[
			{name:'tilde'},
			{name:'n1'},
			{name:'n2'},
			{name:'n3'},
			{name:'n4'},
			{name:'n5'},
			{name:'n6'},
			{name:'n7'},
			{name:'n8'},
			{name:'n9'},
			{name:'n0'},
			{name:'minus'},
			{name:'equal'},
			{name:'backspace'},
			{name:'spacer', size: 1},
			{name:'insert', type:'functions'},
			{name:'home', type:'functions'},
			{name:'page_up', type:'functions'},
			{name:'spacer', size: 1},
			{name:'num_lock'},
			{name:'num_slash'},
			{name:'num_asterisk'},
			{name:'num_minus'}
		],
		[
			{name:'tab'},
			{name:'q'},
			{name:'w'},
			{name:'e'},
			{name:'r'},
			{name:'t'},
			{name:'y'},
			{name:'u'},
			{name:'i'},
			{name:'o'},
			{name:'p'},
			{name:'open_bracket'},
			{name:'close_bracket'},
			{name:'backslash'},
			{name:'spacer', size: 1},
			{name:'del', type:'functions'},
			{name:'end', type:'functions'},
			{name:'page_down', type:'functions'},
			{name:'spacer', size: 1},
			{name:'num_7'},
			{name:'num_8'},
			{name:'num_9'}
		],
		[
			{name:'caps_lock'},
			{name:'a'},
			{name:'s'},
			{name:'d'},
			{name:'f'},
			{name:'g'},
			{name:'h'},
			{name:'j'},
			{name:'k'},
			{name:'l'},
			{name:'semicolon'},
			{name:'quote'},
			{name:'enter'},
			{name:'spacer', size: 8},
			{name:'num_4'},
			{name:'num_5'},
			{name:'num_6'},
			{name:'num_plus'}
		],
		[
			{name:'shift_left', type:'modifiers'},
			{name:'z'},
			{name:'x'},
			{name:'c'},
			{name:'v'},
			{name:'b'},
			{name:'n'},
			{name:'m'},
			{name:'comma'},
			{name:'period'},
			{name:'slash'},
			{name:'shift_right', type:'modifiers'},
			{name:'spacer', size: 3},
			{name:'arrow_top', type:'arrows'},
			{name:'spacer', size: 3},
			{name:'num_1'},
			{name:'num_2'},
			{name:'num_3'}
		],
		[
			{name:'ctrl_left', type:'modifiers'},
			{name:'win_left', type:'modifiers'},
			{name:'alt_left', type:'modifiers'},
			{name:'space'},
			{name:'alt_right', type:'modifiers'},
			{name:'win_right', type:'modifiers'},
			{name:'menu', type:'modifiers'},
			{name:'ctrl_right'},
			{name:'spacer', size: 1},
			{name:'arrow_left', type:'arrows'},
			{name:'arrow_bottom', type:'arrows'},
			{name:'arrow_right', type:'arrows'},
			{name:'spacer', size: 1},
			{name:'num_0'},
			{name:'num_dot'},
			{name:'num_enter'}
		],
	];

	window.keyboard = {
		name: 'g810',
		layout: layout
	};
})();